In [1]:
import numpy as np

In [3]:
lst = ['a', 'b', 'c']

In [6]:
lst.index('f')

ValueError: 'f' is not in list

In [2]:
mat = np.zeros((10, 10), dtype = float)

In [3]:
def add_connection(mat, i, j, type = 'a'):
    if isinstance(j, int):
        j = [j]
    if type == 'a':
        divby = 1.0
    else:
        divby = 1.0*len(j)
    mat[i, j] += 1.0/divby
    return mat

In [4]:
mat = add_connection(mat, 0, 1)

In [5]:
mat = add_connection(mat, 1, [2, 3], 'o')

In [6]:
mat = add_connection(mat, 2, [4, 5])

In [7]:
mat = add_connection(mat, 3, [6, 7])

In [8]:
mat = add_connection(mat, 4, 8)

In [9]:
mat = add_connection(mat, 5, 9)

In [11]:
mat = add_connection(mat, 6, [7, 8, 9], 'o')

In [12]:
mat

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.       

In [14]:
mat = add_connection(mat, 8, 9, 'o')

In [15]:
mat

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.5       , 0.5       , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.       

In [16]:
ii = np.zeros((10,))

In [17]:
ii[0] = 1

In [19]:
np.dot(ii, mat)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.dot(ii, mat@mat)

array([0. , 0. , 0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. ])

In [21]:
np.dot(ii, mat@mat@mat)

array([0. , 0. , 0. , 0. , 0.5, 0.5, 0.5, 0.5, 0. , 0. ])

In [22]:
np.dot(ii, mat@mat@mat@mat)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16666667, 0.66666667, 0.66666667])